"""initial schema

Revision ID: 12ad886508e4
Revises: 
Create Date: 2026-06-30 07:51:21.998138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ad886508e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('local_image_paths',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('local_image_paths',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))

    # ### end Alembic commands ###
